name: delete-old-runs
on:
  schedule:
    - cron: '0,10,20,30,40,50 * * * *'
  workflow_dispatch: null

jobs:
  delete-old-runs:
    name: delete-old-runs
    runs-on: "ubuntu-latest"
    steps:
      - name: install micromamba
        uses: mamba-org/provision-with-micromamba@main
        environment-file: .github/delete-old-runs-env.yml

      - name: delete runs
        shell: bash -l {0}
        run: python scripts/delete_old_runs.py
        env:
          GITHUB_TOKEN: ${{ secrets.AUTOTICK_BOT_TOKEN }}
