name: keepalive
on:
  schedule:
    - cron: "0 0 * * *"
# the keepalive-workflow is a GitHub action to prevent GitHub from suspending
# your cronjob based triggers due to repository inactivity


jobs:
  cronjob-based-github-action:
    name: Cronjob based github action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: gautamkrishnar/keepalive-workflow@v1
